#!/bin/sh

. "$PROJECT_ROOT/common.sh"

[ $NODEPS ] || TOOLCHAIN="$TOOLCHAIN" "$ROOT/build.sh" "libgraphene"

TARGET_SOURCES="
	$PROJECT_ROOT/src/unity.c
"

TARGET_OBJECTS="$(OBJECTS "$TARGET_FLAGS" $TARGET_SOURCES)"

EXEC "$AR" -rcs "$LIB/$TARGET.a.$TARGET_VER" $TARGET_OBJECTS
EXEC "$RANLIB" "$LIB/$TARGET.a.$TARGET_VER"

EXEC ln -sf "$TARGET.a.$TARGET_VER" "$LIB/$TARGET.a.$TARGET_VER_MAJOR"
EXEC ln -sf "$TARGET.a.$TARGET_VER_MAJOR" "$LIB/$TARGET.a"
